#ifndef FONTS_H
#define FONTS_H

#define FNT_PTSANS_CAPTION		"PTC55F"
#define FNT_PTSANS_CAPTION_BOLD		"PTC75F"
#define FNT_PTSANS_NARROW		"PTN57F"
#define FNT_PTSANS_NARROW_BOLD		"PTN77F"
#define FNT_PTSANS_NORMAL		"PTS55F"
#define FNT_PTSANS_ITALIC		"PTS56F"
#define FNT_PTSANS_BOLD			"PTS75F"
#define FNT_PTSANS_BOLD_ITALIC		"PTS76F"
#define FNT_SEGOERG			"SegoeRg"
#define FNT_SEGOEUI			"SegoeUI"
#define FNT_SEGOEUI_ITALIC		"SegoeUII"
#define FNT_SEGOEUI_BOLD		"SegoeUIB"

#endif // FONTS_H
