#ifndef DEF_NOTIFICATIONDATAROLES_H
#define DEF_NOTIFICATIONDATAROLES_H

enum NotificationDataRoles {
	NDR_STREAM_JID,
	NDR_CONTACT_JID,
	NDR_ICON,
	NDR_ICON_KEY,
	NDR_ICON_STORAGE,
	NDR_ROSTER_NOTIFY_ORDER,
	NDR_ROSTER_TOOLTIP,
	NDR_POPUP_IMAGE,
	NDR_POPUP_CAPTION,
	NDR_POPUP_TITLE,
	NDR_POPUP_TEXT,
	NDR_POPUP_TIMEOUT,
	NDR_SOUND_FILE,
	NDR_TABPAGENOTIFY_PRIORITY,
	NDR_TABPAGENOTIFY_ICONBLINK,
	NDR_TABPAGENOTIFY_TOOLTIP,
	NDR_TABPAGENOTIFY_STYLEKEY,
	NDR_USER_ROLES = 32,
	NDR_SUBSCRIPTION_TEXT
};

#endif
