#ifndef DEF_NOTIFICATIONDATAROLES_H
#define DEF_NOTIFICATIONDATAROLES_H

enum NotificationTypes {
	NT_UNKNOWN,
	NT_CHATMESSAGE,
	NT_AUTH,
	NT_CAPTCHA,
	NT_FILETRANSFER,
	NT_CONFERENCE,
	NT_INVITATION,
	NT_MESSAGE,
	NT_PRIVATE_MESSAGE,
	NT_ERROR
};

enum NotificationDataRoles {
	NDR_STREAM_JID,
	NDR_CONTACT_JID,
	NDR_ICON,
	NDR_ICON_KEY,
	NDR_ICON_STORAGE,
	NDR_ROSTER_NOTIFY_ORDER,
	NDR_ROSTER_TOOLTIP,
	NDR_POPUP_IMAGE,
	NDR_POPUP_CAPTION,
	NDR_POPUP_TITLE,
	NDR_POPUP_TEXT,
	NDR_POPUP_TIMEOUT,
	NDR_TRAY_TOOLTIP,
	NDR_SOUND_FILE,
	NDR_TABPAGE_PRIORITY,
	NDR_TABPAGE_ICONBLINK,
	NDR_TABPAGE_TOOLTIP,
	NDR_TABPAGE_STYLEKEY,
	NDR_TYPE,
	NDR_USER_ROLES = 32,
	NDR_SUBSCRIPTION_TEXT
};

#endif
