#ifndef PJSIPDEFINES_H
#define PJSIPDEFINES_H

#define HAS_VIDEO_SUPPORT	1

#define SIP_DOMAIN		"vsip.rambler.ru"

#define DEFAULT_CAP_DEV		PJMEDIA_VID_DEFAULT_CAPTURE_DEV
#define DEFAULT_REND_DEV	PJMEDIA_VID_DEFAULT_RENDER_DEV

#endif // PJSIPDEFINES_H
